services:
  - type: web
    name: zerx-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: LINK_SECRET
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DB_PATH
        value: /opt/render/project/src/zerx.db